### ISSUE TITLE
Showing the sessionizer doesn't work after adding a path

### ISSUE THREAD

**Issue by sondrejk** [mikkasendke/sessionizer.wezterm#4]
I copied the config, but when i add the path

`/home/user/repos`

Then the hotkey for showing the sessionizer doesn't work anymore.

i have fd version 10.2.0

**Comment by mikkasendke** [comment]
Okay, thank you for opening the issue I will look into it later today.

**Comment by mikkasendke** [comment]
Can you try putting `sessionizer.apply_to_config(config)` below your `config.keys = { ... }` and remove any other calls to the function. If you have this already and it does not work it would be helpful if you could send a config in which the problem occurs, thank you

**Comment by sondrejk** [comment]
That didnt work unfortunately...

Here is my config

``` lua
-- Pull the wezterm api
local wezterm = require("wezterm")
local act = wezterm.action
local mux = wezterm.mux

-- This table holds configuration
local config = {}

-- Better error messages by using the config builder
if wezterm.config_builder then
	config = wezterm.config_builder()
end

--------------------
-- STARTUP CONFIG --
--------------------

local is_linux <const> = wezterm.target_triple:find("linux") ~= nil

if not is_linux then
	config.default_domain = "WSL:Ubuntu"
	wsl_domains = {
		{
			name = "WSL:Ubuntu-22.04",
			distribution = "Ubuntu-22.04",
			default_cwd = "/home/sondrejk",
		},
	}
else
	config.default_domain = "local"
end

------------------------
-- APPEARANCE CONFIGS --
------------------------

config.font = wezterm.font("JetBrains Mono")
config.color_scheme = "GruvboxDark"

----------
-- TABS --
----------

local function get_current_working_dir(tab)
	local current_dir = tab.active_pane and tab.active_pane.current_working_dir or { file_path = "" }
	local HOME_DIR = string.format("file://%s", os.getenv("HOME"))

	return current_dir == HOME_DIR and "." or string.gsub(current_dir.file_path, "(.*[/\\])(.*)", "%2")
end

-- tab title
wezterm.on("format-tab-title", function(tab, tabs, panes, config, hover, max_width)
	local has_unseen_output = false
	if not tab.is_active then
		for _, pane in ipairs(tab.panes) do
			if pane.has_unseen_output then
				has_unseen_output = true
				break
			end
		end
	end

	local cwd = wezterm.format({
		{ Attribute = { Intensity = "Bold" } },
		{ Text = get_current_working_dir(tab) },
	})

	local title = string.format(" [%s] %s", tab.tab_index + 1, cwd)

	if has_unseen_output then
		return {
			{ Foreground = { Color = "#8866bb" } },
			{ Text = title },
		}
	end

	return {
		{ Text = title },
	}
end)

--------------
-- VIM MODE --
--------------

-- WIP

----------------
-- WORKSPACES --
----------------

-- load plugin
local workspace_switcher = wezterm.plugin.require("https://github.com/MLFlexer/smart_workspace_switcher.wezterm")
config.default_workspace = "~/repos"

local sessionizer = wezterm.plugin.require("https://github.com/mikkasendke/sessionizer.wezterm")
sessionizer.config = {
	paths = {
		"/home/sondrejk/repos/",
	},
}

-------------
-- KEYMAPS --
-------------

-- timeout_milliseconds defaults to 1000 and can be omitted
config.leader = { key = "a", mods = "CTRL", timeout_milliseconds = 1000 }
config.keys = {

	-- Making panes and exiting them
	{ key = "v", mods = "LEADER", action = wezterm.action.SplitHorizontal({ domain = "CurrentPaneDomain" }) },
	{ key = "h", mods = "LEADER", action = wezterm.action.SplitVertical({ domain = "CurrentPaneDomain" }) },
	{ key = "q", mods = "LEADER", action = wezterm.action.CloseCurrentPane({ confirm = false }) },

	-- Tabs
	{ key = "t", mods = "LEADER", action = act.SpawnTab("DefaultDomain") },

	-- Send "CTRL-A" to the terminal when pressing CTRL-A, CTRL-A
	{ key = "a", mods = "LEADER", action = wezterm.action.SendKey({ key = "a", mods = "CTRL" }) },

	-- Navigation and resizing panes using hjkl
	{ key = "h", mods = "SHIFT|CTRL", action = act.ActivatePaneDirection("Left") },
	{ key = "h", mods = "SHIFT|ALT|CTRL", action = act.AdjustPaneSize({ "Left", 10 }) },
	{ key = "l", mods = "SHIFT|CTRL", action = act.ActivatePaneDirection("Right") },
	{ key = "l", mods = "SHIFT|ALT|CTRL", action = act.AdjustPaneSize({ "Right", 10 }) },
	{ key = "k", mods = "SHIFT|CTRL", action = act.ActivatePaneDirection("Up") },
	{ key = "k", mods = "SHIFT|ALT|CTRL", action = act.AdjustPaneSize({ "Up", 10 }) },
	{ key = "j", mods = "SHIFT|CTRL", action = act.ActivatePaneDirection("Down") },
	{ key = "j", mods = "SHIFT|ALT|CTRL", action = act.AdjustPaneSize({ "Down", 10 }) },

	-- Navigating tabs
	{ key = "h", mods = "SHIFT|ALT", action = act.ActivateTabRelative(-1) },
	{ key = "l", mods = "SHIFT|ALT", action = act.ActivateTabRelative(1) },

	-- Workspace hotkeys
	{ key = "d", mods = "LEADER", action = act.SwitchToWorkspace({ name = "dotfiles" }) },
	{ key = "s", mods = "LEADER", action = workspace_switcher.switch_workspace() },
	{ key = "f", mods = "LEADER", action = sessionizer.show },
}

sessionizer.apply_to_config(config, true)
return config
```

I if i keep the sessionizer.config paths empty, then i can open the sessionizer, but as soon as i add a path then i can't open it anymore

Thank you very much for looking into this :)

**Comment by mikkasendke** [comment]
oh yeah removing the `, true` from `sessionizer.apply_to_config(config, true)` so it's just `sessionizer.apply_to_config(config)` should fix it (the true is to disable default binds). There will be a big change coming soon though which might also alter this but I'll try to stay backwards compatible and you'd have to manually update anyway so yeah

**Comment by mikkasendke** [comment]
Oh okay, unfortunately I can not replicate this, but it might be that it fails to run `fd` this happened to someone before, to be sure you could look at the debug overlay (ctrl+shift+p) the error message is something like _no such file or directory (os error 2)_. If it is this you can run `which fd` in your terminal and put the path in here:
```lua
sessionizer.config = {
    paths = {
        "/home/sondrejk/repos/",
    },
    command_options = {
        fd_path = -- here your fd path
    }
}
```
there is an update coming soon though which will fix such things

**Comment by mikkasendke** [comment]
it should at least fail in the scope where we run fd

**Comment by sondrejk** [comment]
Sorry for the late reply!

I did as you suggested and got this:
```
> sessionizer.show
runtime error: [string "repl"]:1: attempt to index a nil value (global 'sessionizer')
stack traceback:
        [string "repl"]:1: in main chunk
12:15:49.670 ERROR wezterm_gui::termwindow > while processing user-defined-0 event: No such file or directory (os error 2)
stack traceback:
        [C]: in local 'poll'
        [string "?"]:4: in function 'wezterm.run_child_process'
        ...esZssessionizersDswezterm/plugin/sessionizer/entries.lua:70: in upvalue 'apply_commands'
        ...esZssessionizersDswezterm/plugin/sessionizer/entries.lua:90: in function 'sessionizer.entries.get_entries'
        ...omsZsmikkasendkesZssessionizersDswezterm/plugin/init.lua:21: in function <...omsZsmikkasendkesZssessionizersDswezterm/plugin/init.lua:19>
```

I did `which fd` and got this path:
`/home/linuxbrew/.linuxbrew/bin/fd`

Added this to my config:
```
sessionizer.config = {
  paths = {
    "/home/sondrejk/repos/",
  },
  command_options = {
    fd_path = "/home/linuxbrew/.linuxbrew/bin/fd",
  },
}
```
And yet it still doesn't work...

Also tried uninstalling fd and installing it again using apt this time. I changed the path in the config, but still no luck. Still the same error in the debug overlay

**Comment by itsisak** [comment]
I faced the same problem, for me what solved it was cloning the repo and using that instead of the github link.

**Comment by mikkasendke** [comment]
@sondrejk no problem. This is a bit weird, it definitely fails to find the fd binary, `[string "?"]:4: in function 'wezterm.run_child_process'` and with the correct absolute path it should be able to find it. Now there are two options for what it could be either the fd_path option is not present in your local version (it was added a while ago) or there is some kind of permission issue. What @itsisak said would probably fix both (but it is not the cleanest solution), but what also might fix it (if it only is because the option is not present) is updating the plugin. There is require "wezterm".plugin.update_all() but to me the easiest was just deleting `~/.local/share/wezterm/plugins/httpssCssZssZsgithubsDscomsZsmikkasendkesZssessionizersDswezterm` which is where wezterm automatically downloads the plugin, and it will clone the newer version (idk if the last directory is always the same but it should be similar). Thanks for your patience

**Comment by itsisak** [comment]
@mikkasendke Deleting this folder worked! However the `~/.local/share/wezterm/plugins/` did not exist for me (on mac), but I found the corresponing folder at `~/Library/Application Support/wezterm/plugins/httpssCssZssZsgithubsDscomsZsmikkasendkesZssessionizersDswezterm`. Perhaps this is an issue for plugins on macs in general and not only this one.

**Comment by sondrejk** [comment]
Got it working after updating the plugin, thank you very much for your help!
